str_heroes = 
[
  "Earthshaker",
  "Sven",
  "Axe",
  "Pudge",
  "Tiny",
  "Kunkka",
  "Sand King",
  "Slardar",
  "Beastmaster",
  "Dragon Knight",
  "Tidehunter",
  "Wraith King",
  "Clockwerk", 
  "Omniknight",
  "Lifestealer",
  "Night Stalker",
  "Huskar",
  "Alchemist",
  "Doom",
  "Spirit Breaker",
  "Brewmaster",
  "Treant Protector",
  "Lycan",
  "Chaos Knight",
  "Io",
  "Centaur Warrunner",
  "Undying",
  "Magnus",
  "Timbersaw",
  "Bristleback",
  "Abaddon",
  "Tusk",
  "Elder Titan",
  "Legion Commander",
  "Earth Spirit",
  "Phoenix"
]

agi_heroes =
[
  "Anti-Mage",
  "Drow Ranger",
  "Bloodseeker",
  "Shadow Fiend",
  "Juggernaut",
  "Mirana",
  "Razor",
  "Venomancer",
  "Morphling",
  "Phantom Lancer",
  "Faceless Void",
  "Phantom Assassin",
  "Vengeful Spirit",
  "Riki",
  "Viper",
  "Clinkz",
  "Sniper",
  "Templar Assassin",
  "Broodmother",
  "Weaver",
  "Luna",
  "Bounty Hunter",
  "Spectre",
  "Meepo",
  "Ursa",
  "Gyrocopter",
  "Nyx Assassin",
  "Slark",
  "Lone Druid",
  "Naga Siren",
  "Medusa",
  "Terrorblade",
  "Troll Warlord",
  "Ember Spirit"
]

int_heroes = 
[
  "Crystal Maiden",
  "Puck",
  "Bane",
  "Lich",
  "Storm Spirit",
  "Windranger",
  "Lion",
  "Witch Doctor",
  "Zeus",
  "Lina",
  "Enigma",
  "Necrophos",
  "Shadow Shaman",
  "Tinker",
  "Warlock",
  "Queen of Pain",
  "Nature's Prophet",
  "Enchantress",
  "Death Prophet",
  "Pugna",
  "Jakiro",
  "Chen",
  "Dazzle",
  "Leshrac",
  "Silencer",
  "Ogre Magi",
  "Dark Seer",
  "Batrider",
  "Rubick",
  "Disruptor",
  "Ancient Apparition",
  "Invoker",
  "Keeper of the Light",
  "Skywrath Mage",
  "Outworld Devourer",
  "Shadow Demon",
  "Oracle",
  "Techies",
  "Visage",
  "Winter Wyvern"
]

arrays = [str_heroes, agi_heroes, int_heroes]
attribute = 0
arrays.each do |heroes|
  heroes.each do |hero_name|
    hero = Hero.where(name: hero_name).first
    hero.main_attribute = attribute
    hero.save
  end
  attribute += 1
end